### ISSUE TITLE
Is it Possible?

### ISSUE THREAD

**Issue by zafyraminx** [gree/pure2d#10]
I am trying to play a Video in my project and I think it is possible to play with opengl instead of using another view which is VideoView. And i look in the pure2d library and it has Sound media only so i try to search on the net and i saw some explanation and example. Is it possible to play with the mScene in your project? or should I edit your library so I can play Video there, but i think it will take a few time to do. What do you think? or is there a function in the library that can handle video play?

**Comment by longngo78** [comment]
Sorry, Pure2d doesn't support video. You probably want to have your video played on top of the scene...

**Comment by zafyraminx** [comment]
Ohh I see, yes I want to play video om the scene but i dont know if it can be done by your library.
