### ISSUE TITLE
LWF background can't be transparent

### ISSUE THREAD

**Issue by zafyraminx** [gree/pure2d#8]
Hello, i am using your engine since last year then now i am creating a feature with camera preview and some animation, then i am using a transparent gl so that my xml can see at the back, all of the animation is good but when i am trying to use LWF it has black background and aside from that if it is use for transparent its color is different. is there any chance to use camera to the view instead of using my xml as a guide or is there any possibility to make the LWF outout transparent?

**Comment by longngo78** [comment]
That could be an issue with the LWF plugin itself. To recap, if you remove the LWF, everything seems fine? Also you have a screenshot?

**Comment by zafyraminx** [comment]
![screenshot from 2015-02-04 10 17 11](https://cloud.githubusercontent.com/assets/10840583/6033944/8d82b2bc-ac57-11e4-81d3-b5927489836c.png)
it looks like that if i use LWF, but if i use other animation it is fine.

**Comment by longngo78** [comment]
Most likely this is a LWF issue. You probably want to file an issue here:
https://github.com/gree/lwf

**Comment by zafyraminx** [comment]
Ohh I see, I try to use Skeletal animation too because it is fine with the transparency but the problem is i dont know how to make a ani file
![screenshot from 2015-02-04 10 38 47](https://cloud.githubusercontent.com/assets/10840583/6034196/d06bf09a-ac5a-11e4-853e-3b03ccbda569.png)

**Comment by longngo78** [comment]
It is a proprietary format and deprecated. LWF is the way to go for this type of animation. Sorry I can't help you with this.

**Comment by zafyraminx** [comment]
I see anyway thanks for your response.
