### ISSUE TITLE
Can't reload texture.

### ISSUE THREAD

**Issue by zafyraminx** [gree/pure2d#9]
Hello, I am having a problem in loading texture, Is there a way to reload texture? because i am trying to load a texture outside onsurfacecreated but it doesn't work, because i want to change some texture in running time is there a way or it is really impossible? I just want to change one of the image source in the loadtexture that's why i am asking.

**Comment by longngo78** [comment]
You can always load Texture anytime after onSurfaceCreated() as long as you do on the GL Thread. Use  surface.queueEvent() to queue the loading.

**Comment by zafyraminx** [comment]
Thanks for your time to answer I get it now, and it is working. Thanks a lot.
